'use client';
import {useState} from 'react';
import {motion,useReducedMotion} from 'framer-motion';
import {Code2,ExternalLink,Film,ImageIcon,FolderOpen,Check} from 'lucide-react';
import {FaGithub} from 'react-icons/fa';
import {projectEvidence} from '../content/media';
import {projects} from '../content/portfolio';
type Project=(typeof projects)[number];
export default function ProjectShowcase({project,initialTab='results'}:{project:Project;initialTab?:'overview'|'results'|'code'}){
 const [tab,setTab]=useState<'overview'|'results'|'code'>(initialTab);const reduced=useReducedMotion();const evidence=projectEvidence[project.id];
 const tabs=[['overview','Overview'],['results','Project results'],['code','Source code']] as const;
 return <><span className="eyebrow">{project.type} / {project.status}</span><h2>{project.name}</h2><div className="project-view-tabs" role="tablist" aria-label={project.name+' details'}>{tabs.map(([id,label],i)=><button id={'project-tab-'+id} type="button" key={id} role="tab" aria-selected={tab===id} aria-controls={'project-panel-'+id} tabIndex={tab===id?0:-1} onClick={()=>setTab(id)} onKeyDown={e=>{let n=i;if(e.key==='ArrowRight')n=(i+1)%tabs.length;else if(e.key==='ArrowLeft')n=(i+tabs.length-1)%tabs.length;else if(e.key==='Home')n=0;else if(e.key==='End')n=tabs.length-1;else return;e.preventDefault();setTab(tabs[n][0]);document.getElementById('project-tab-'+tabs[n][0])?.focus()}}>{label}</button>)}</div>
 <div className="project-tab-body" role="tabpanel" id={'project-panel-'+tab} aria-labelledby={'project-tab-'+tab} tabIndex={0}>
 {tab==='overview'&&<><p>{project.description}</p><div className="tags">{project.tech.map(t=><span key={t}>{t}</span>)}</div>{evidence?.notes&&<ul className="project-evidence-notes">{evidence.notes.map(n=><li key={n}>{n}</li>)}</ul>}</>}
 {tab==='results'&&<><p className="project-result-summary">{evidence?.summary||'Screenshots, output videos, and measured results have not been supplied for this project yet.'}</p>{evidence?.media.length?evidence.media.map((m,i)=><motion.figure className="result-media-frame" key={m.src} initial={{opacity:reduced?1:0,y:reduced?0:12}} animate={{opacity:1,y:0}} transition={{duration:.4,delay:i*.08}}><h3 className="result-image-title">{m.title}</h3>{m.type==='video'?<video controls playsInline muted preload="none" poster={m.poster} aria-label={m.alt}><source src={m.src} type="video/mp4"/><p>Your browser cannot play this video. <a href={m.src}>Open the video file</a>.</p></video>:<a href={m.src} target="_blank" rel="noreferrer" aria-label={'View full-size '+m.title}><img src={m.src} alt={m.alt} loading="lazy"/></a>}<figcaption><h3>{m.type==='video'?<Film size={18}/>:<ImageIcon size={18}/>} {m.title}</h3><p>{m.caption}</p><a href={m.src} target="_blank" rel="noopener noreferrer">Open original media <ExternalLink size={13}/></a></figcaption></motion.figure>):project.image?<figure className="result-media-frame"><img src={project.image} alt={project.name+' project preview'}/><figcaption>{project.subtitle}</figcaption></figure>:<div className="results-empty"><ImageIcon size={34}/><h3>Results gallery</h3><p>Project screenshots and demonstrations will appear here once provided.</p></div>}</>}
 {tab==='code'&&<>{evidence?.files.length?<div className="source-files">{evidence.files.map(f=><a key={f.url} href={f.url} target="_blank" rel="noopener noreferrer"><Code2 size={18}/><span>{f.label}</span><ExternalLink size={16}/></a>)}</div>:<div className="results-empty"><FolderOpen size={34}/><h3>Project source not linked yet</h3><p>No project-specific public repository has been confirmed. You can still visit SV’s GitHub profile below.</p></div>}</>}
 </div><div className="modal-actions project-persistent-links"><a className="button secondary" href={project.github} target="_blank" rel="noopener noreferrer"><FaGithub size={17}/>View project on GitHub</a></div></>
}
