'use client';
import {Canvas,useFrame} from '@react-three/fiber';
import {useEffect,useRef,useState,Component,ReactNode} from 'react';
import * as THREE from 'three';
import gsap from 'gsap';
const entries=[['Python','Py'],['React','Re'],['Node.js','Js'],['GitHub','Gh'],['Docker','Dk'],['Linux','Lx'],['OpenAI','AI'],['TensorFlow','Tf'],['MongoDB','Mo'],['PostgreSQL','Pg'],['Firebase','Fb'],['AWS','AWS']] as const;
function Sphere({drag,reduced,labels}:{drag:React.RefObject<{x:number;y:number;down:boolean}>,reduced:boolean,labels:React.RefObject<HTMLDivElement|null>}){const group=useRef<THREE.Group>(null);const worldPosition=useRef(new THREE.Vector3());const cameraPosition=useRef(new THREE.Vector3());const center=useRef(new THREE.Vector3());const direction=useRef(new THREE.Vector3());const radial=useRef(new THREE.Vector3());useEffect(()=>{if(!group.current||reduced)return;const t=gsap.fromTo(group.current.scale,{x:.85,y:.85,z:.85},{x:1,y:1,z:1,duration:1.5,ease:'power2.out'});return()=>{t.kill()}},[reduced]);useFrame(({camera,size},dt)=>{if(!group.current)return;if(!drag.current.down)group.current.rotation.y+=dt*.24;group.current.rotation.y+=drag.current.x;group.current.rotation.x+=drag.current.y;drag.current.x=0;drag.current.y=0;group.current.updateMatrixWorld();camera.getWorldPosition(cameraPosition.current);group.current.localToWorld(center.current.set(0,0,0));direction.current.subVectors(cameraPosition.current,center.current).normalize();const elements=labels.current?.querySelectorAll<HTMLElement>('[data-tech-index]');if(!elements)return;elements.forEach(element=>{const index=Number(element.dataset.techIndex);const y=1-(index/(entries.length-1))*2;const radius=Math.sqrt(1-y*y);const theta=Math.PI*(3-Math.sqrt(5))*index;worldPosition.current.set(Math.cos(theta)*radius*2,y*2,Math.sin(theta)*radius*2);group.current!.localToWorld(worldPosition.current);const front=radial.current.subVectors(worldPosition.current,center.current).normalize().dot(direction.current);worldPosition.current.project(camera);element.style.left=`${(worldPosition.current.x+1)*size.width/2}px`;element.style.top=`${(1-worldPosition.current.y)*size.height/2}px`;element.style.opacity=String(Math.max(0,Math.min(.95,(front+.05)*1.4)));element.style.visibility=front<-.08||worldPosition.current.z>1?'hidden':'visible';element.style.zIndex=front>.3?'2':'0'})});return <group ref={group}><mesh><sphereGeometry args={[1.9,16,12]}/><meshBasicMaterial color="#164453" wireframe transparent opacity={.2}/></mesh></group>}
class Boundary extends Component<{children:ReactNode},{failed:boolean}>{state={failed:false};static getDerivedStateFromError(){return{failed:true}}render(){return this.state.failed?<div className="sphere-fallback">TECHNOLOGY / CONNECTED</div>:this.props.children}}
export default function TechSphere(){const [reduced,setReduced]=useState(true);const [visible,setVisible]=useState(false);const root=useRef<HTMLDivElement>(null);const labelLayer=useRef<HTMLDivElement>(null);const drag=useRef({x:0,y:0,down:false});const pointer=useRef({x:0,y:0});useEffect(()=>{const media=matchMedia('(prefers-reduced-motion: reduce)');setReduced(media.matches);const change=()=>setReduced(media.matches);media.addEventListener('change',change);const observer=new IntersectionObserver(([e])=>setVisible(e.isIntersecting),{rootMargin:'150px'});if(root.current)observer.observe(root.current);return()=>{observer.disconnect();media.removeEventListener('change',change)}},[]);return <div ref={root} style={{width:'100%',height:'100%',touchAction:'pan-y',position:'relative'}} aria-label="Rotating technology sphere; all technologies are also listed as text" onPointerDown={e=>{drag.current.down=true;pointer.current={x:e.clientX,y:e.clientY};e.currentTarget.setPointerCapture(e.pointerId)}} onPointerMove={e=>{if(drag.current.down){drag.current.x=(e.clientX-pointer.current.x)*.005;drag.current.y=(e.clientY-pointer.current.y)*.003;pointer.current={x:e.clientX,y:e.clientY}}}} onPointerUp={()=>drag.current.down=false} onPointerCancel={()=>drag.current.down=false}><Boundary>{visible&&<Canvas dpr={[1,1.5]} camera={{position:[0,0,6.4],fov:46}} gl={{alpha:true,antialias:true,powerPreference:'low-power'}}><Sphere drag={drag} reduced={reduced} labels={labelLayer}/></Canvas>}</Boundary><div ref={labelLayer} className="tech-sphere-labels" aria-hidden="true">{entries.map(([name,mark],index)=><div className="tech-sphere-label" data-tech-index={index} key={name}><span>{mark}</span><small>{name}</small></div>)}</div></div>}
