'use client';
import {Canvas,useFrame} from '@react-three/fiber';
import {useEffect,useRef,useState,Component,ReactNode} from 'react';
import * as THREE from 'three';
import gsap from 'gsap';
import {renderToStaticMarkup} from 'react-dom/server';
import {SiPython,SiReact,SiNodedotjs,SiGithub,SiDocker,SiLinux,SiTensorflow,SiMongodb,SiPostgresql,SiFirebase} from 'react-icons/si';
import {TbBrandOpenai as SiOpenai} from 'react-icons/tb';
import {FaAws as SiAmazonwebservices} from 'react-icons/fa';
const entries=[['Python',SiPython],['React',SiReact],['Node.js',SiNodedotjs],['GitHub',SiGithub],['Docker',SiDocker],['Linux',SiLinux],['OpenAI',SiOpenai],['TensorFlow',SiTensorflow],['MongoDB',SiMongodb],['PostgreSQL',SiPostgresql],['Firebase',SiFirebase],['AWS',SiAmazonwebservices]] as const;
function Label({index}:{index:number}){const [texture,setTexture]=useState<THREE.CanvasTexture|null>(null);useEffect(()=>{const [name,Icon]=entries[index];const canvas=document.createElement('canvas');canvas.width=320;canvas.height=160;const ctx=canvas.getContext('2d')!;const img=new Image();let cancelled=false;let tex:THREE.CanvasTexture|undefined;img.onload=()=>{if(cancelled)return;ctx.drawImage(img,134,8,52,52);ctx.fillStyle='#a9e9f4';ctx.font='500 23px sans-serif';ctx.textAlign='center';ctx.fillText(name,160,100);tex=new THREE.CanvasTexture(canvas);tex.colorSpace=THREE.SRGBColorSpace;setTexture(tex)};img.src='data:image/svg+xml;charset=utf-8,'+encodeURIComponent(renderToStaticMarkup(<Icon color="#00d9f0" size={64}/>));return()=>{cancelled=true;tex?.dispose()}},[index]);const y=1-(index/(entries.length-1))*2;const radius=Math.sqrt(1-y*y);const theta=Math.PI*(3-Math.sqrt(5))*index;return <sprite position={[Math.cos(theta)*radius*2,y*2,Math.sin(theta)*radius*2]} scale={[1.35,.68,1]}><spriteMaterial map={texture} transparent opacity={.95} depthWrite={false}/></sprite>}
function Sphere({drag,reduced}:{drag:React.RefObject<{x:number;y:number;down:boolean}>,reduced:boolean}){const group=useRef<THREE.Group>(null);useEffect(()=>{if(!group.current||reduced)return;const t=gsap.fromTo(group.current.scale,{x:.85,y:.85,z:.85},{x:1,y:1,z:1,duration:1.5,ease:'power2.out'});return()=>{t.kill()}},[reduced]);useFrame((_,dt)=>{if(group.current){if(!reduced&&!drag.current.down)group.current.rotation.y+=dt*.1;group.current.rotation.y+=drag.current.x;group.current.rotation.x+=drag.current.y;drag.current.x=0;drag.current.y=0}});return <group ref={group}><mesh><sphereGeometry args={[1.9,16,12]}/><meshBasicMaterial color="#164453" wireframe transparent opacity={.2}/></mesh>{entries.map((e,i)=><Label index={i} key={e[0]}/>)}</group>}
class Boundary extends Component<{children:ReactNode},{failed:boolean}>{state={failed:false};static getDerivedStateFromError(){return{failed:true}}render(){return this.state.failed?<div className="sphere-fallback">TECHNOLOGY / CONNECTED</div>:this.props.children}}
export default function TechSphere(){const [reduced,setReduced]=useState(true);const [visible,setVisible]=useState(false);const root=useRef<HTMLDivElement>(null);const drag=useRef({x:0,y:0,down:false});const pointer=useRef({x:0,y:0});useEffect(()=>{const media=matchMedia('(prefers-reduced-motion: reduce)');setReduced(media.matches);const change=()=>setReduced(media.matches);media.addEventListener('change',change);const observer=new IntersectionObserver(([e])=>setVisible(e.isIntersecting),{rootMargin:'150px'});if(root.current)observer.observe(root.current);return()=>{observer.disconnect();media.removeEventListener('change',change)}},[]);return <div ref={root} style={{width:'100%',height:'100%',touchAction:'pan-y'}} aria-label="Rotating technology sphere; all technologies are also listed as text" onPointerDown={e=>{drag.current.down=true;pointer.current={x:e.clientX,y:e.clientY};e.currentTarget.setPointerCapture(e.pointerId)}} onPointerMove={e=>{if(drag.current.down){drag.current.x=(e.clientX-pointer.current.x)*.005;drag.current.y=(e.clientY-pointer.current.y)*.003;pointer.current={x:e.clientX,y:e.clientY}}}} onPointerUp={()=>drag.current.down=false} onPointerCancel={()=>drag.current.down=false}><Boundary>{visible&&<Canvas dpr={[1,1.5]} camera={{position:[0,0,6.4],fov:46}} gl={{alpha:true,antialias:true,powerPreference:'low-power'}}><Sphere drag={drag} reduced={reduced}/></Canvas>}</Boundary></div>}
